/* Make sure we recognize all the different ways a variable
 * can be used/generated by the instructions introduced in Part II
 * (type conversions, AddPtr, etc) */

long test_sign_extend(int flag, int arg) {
    if (flag) {
        arg = -1;  
                   
                   
    }
    return (long)arg;
}

unsigned long test_zero_extend(int flag, unsigned int arg) {
    if (flag) {
        arg = 4294967295U;  
                            
                            
    }
    return (unsigned long)arg;
}

int test_double_to_int(int flag, double arg) {
    if (flag) {
        arg = 225.5;  
                      
                      
    }
    return (int)arg;
}

double test_int_to_double(int flag, long arg) {
    if (flag) {
        arg = 500000l;  
                        
                        
    }
    return (double)arg;
}

unsigned long test_double_to_uint(int flag, double arg) {
    if (flag) {
        arg = 1844674407370955264.;  
    }
    return (unsigned long)arg;
}

double test_uint_to_double(int flag, unsigned int arg) {
    if (flag) {
        arg = 2147483650u;  
    }
    return (double)arg;
}

char test_truncate(int flag, long arg) {
    if (flag) {
        arg = 300;  
                    
                    
    }
    return (char)arg;
}

double *test_add_ptr(int flag, double *ptr, long index) {
    static double arr[3] = {1.0, 2.0, 3.0};
    if (flag == 0) {
        ptr = arr;  
    } else if (flag == 1) {
        index = 2l;  
    }
    return &ptr[index];
}

struct s {
    int a;
    int b;
    int c;
};

int test_copyfromoffset(int flag, struct s arg) {
    struct s other_struct = {10, 9, 8};
    if (flag) {
        arg = other_struct;  
    }
    return arg.b;
}

struct s test_copytooffset(int flag, int arg) {
    struct s my_struct = {101, 102, 103};
    if (flag) {
        arg = -1;  
    }
    my_struct.b = arg;
    return my_struct;
}


void test_store(int flag, long *ptr1, long *ptr2, long val) {
    if (flag == 1) {
        ptr1 = ptr2;  
    }
    if (flag == 2) {
        val = 77l;  
    }
    *ptr1 = val;
}




int test_load(int flag, int *ptr1, int *ptr2) {
    if (flag) {
        ptr1 = ptr2;  
    }
    return *ptr1;
}

int main(void) {
    if (test_sign_extend(0, -5) != -5l) {
        return 1;  
    }
    if (test_sign_extend(1, -5) != -1l) {
        return 2;  
    }
    if (test_zero_extend(0, 100000u) != 100000ul) {
        return 3;  
    }
    if (test_zero_extend(1, 100000u) != 4294967295UL) {
        return 4;  
    }
    if (test_double_to_int(0, 1000.5) != 1000) {
        return 5;  
    }
    if (test_double_to_int(1, 1000.5) != 225) {
        return 6;  
    }
    if (test_int_to_double(0, 100) != 100.0) {
        return 7;  
    }
    if (test_int_to_double(1, 100) != 500000.0) {
        return 8;  
    }
    if (test_double_to_uint(0, 1234567.8) != 1234567u) {
        return 9; 
    }
    if (test_double_to_uint(1, 1234567.8) != 1844674407370955264u) {
        return 10; 
    }
    if (test_uint_to_double(0, 4294967000U) != 4294967000.) {
        return 11; 
    }
    if (test_uint_to_double(1, 4294967000U) != 2147483650u) {
        return 12; 
    }
    if (test_truncate(0, 500) != -12) {
        return 13;  
    }
    if (test_truncate(1, 500) != 44) {
        return 14;  
    }
    double arr[3] = {4.0, 5.0, 6.0};
    if (*test_add_ptr(0, arr, 1) != 2.0) {
        return 15;  
    }
    if (*test_add_ptr(1, arr, 1) != 6.0) {
        return 16;  
    }
    if (*test_add_ptr(2, arr, 1) != 5.0) {
        return 17;  
    }
    struct s strct = {20, 21, 22};

    if (test_copyfromoffset(0, strct) != 21) {
        return 18;  
    }
    if (test_copyfromoffset(1, strct) != 9) {
        return 19;  
    }
    if (test_copytooffset(0, -10).b != -10) {
        return 20;  
    }
    if (test_copytooffset(1, -10).b != -1) {
        return 21;  
    }
    long l1 = 0l;
    long l2 = 0l;

    test_store(0, &l1, &l2, 5l);
    if (l1 != 5l || l2 != 0l) {
        return 22;  
    }
    test_store(1, &l1, &l2, 6l);
    if (l1 != 5l || l2 != 6l) {
        return 23;  
    }
    test_store(2, &l1, &l2, 5l);
    if (l1 != 77l || l2 != 6l) {
        return 24;  
    }

    int i1 = 2;
    int i2 = 3;

    if (test_load(0, &i1, &i2) != 2) {
        return 25;  
    }
    if (test_load(1, &i1, &i2) != 3) {
        return 26;  
    }

    return 0;  
}